name: Deploy Frontend
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/checkout@v3
      - run: docker build -t filipgavrilovski/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true filipgavrilovski/react-test npm test

      - run: docker build -t filipgavrilovski/multi-client ./client
      - run: docker build -t filipgavrilovski/multi-nginx ./nginx
      - run: docker build -t filipgavrilovski/multi-server ./server
      - run: docker build -t filipgavrilovski/multi-worker ./worker

      - run: docker push filipgavrilovski/multi-client
      - run: docker push filipgavrilovski/multi-nginx
      - run: docker push filipgavrilovski/multi-server
      - run: docker push filipgavrilovski/multi-worker
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-812005588296
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip